Repository IBM/ibm-auditlogging-operator, pull requests merged in 2020-07, with the labels that each got.

#95 bindinfo and external namespace access
  deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml
  go.sum
  pkg/resources/certificates.go
Labels: approved, lgtm, size/S

#96 fix(csv): api version omited on binding
  deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#98 update e2e link/add ingest cm/add ingest cm to bindinfo
  README.md
  deploy/olm-catalog/ibm-auditlogging-operator/3.7.0/ibm-auditlogging-operator.v3.7.0.clusterserviceversion.yaml
  pkg/controller/auditlogging/auditlogging.go
  pkg/resources/configmaps.go
Labels: approved, lgtm, size/S

#100 fix(controller): don't allow auditlogging to run with commonaudit
  go.mod
  go.sum
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/controller/auditlogging/auditlogging_controller_test.go
  pkg/controller/commonaudit/commonaudit_controller.go
  pkg/controller/commonaudit/commonaudit_controller_test.go
Labels: approved, lgtm, size/L

#102 feat(resources): new audit-certs secret managed by operator
  pkg/controller/commonaudit/commonaudit.go
  pkg/controller/commonaudit/commonaudit_controller.go
  pkg/controller/commonaudit/commonaudit_controller_test.go
  pkg/resources/deployments.go
  pkg/resources/secret.go
Labels: approved, lgtm, size/L

#104 ci(prow): push image to artifactory
  Makefile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  common/scripts/config_docker.sh
Labels: approved, lgtm, size/S
