Repository IBM/ibm-auditlogging-operator, pull requests merged in 2020-05, with the labels that each got.

#69 in place update for output plugin configmaps
  Makefile
  README.md
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller_test.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#70 updated ubi8 min images
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
  pkg/controller/auditlogging/auditlogging_controller_test.go
Labels: approved, lgtm, size/XS

#72 preserve output config on update
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller_test.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#71 Doc updates
  .gitignore
  README.md
Labels: approved, lgtm, size/M

#74 csv template update
  README.md
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#73 pull operand images by SHA instead of tag
  Makefile
  common/scripts/get_image_sha.sh
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/auditlogging_types.go
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller_test.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#75 update product version
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#76 update logic for labels/annotations
  pkg/controller/auditlogging/auditlogging.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#77 fix defaults to match doc
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  pkg/controller/auditlogging/auditlogging.go
Labels: approved, lgtm, size/S

#78 fix update status
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller_test.go
Labels: approved, lgtm, size/XS

#79 colon missing in csv
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#80 update csv with operands sha
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  test/e2e/auditlogging_test.go
Labels: approved, lgtm, size/S

#83 update csv to beta channel
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
Labels: approved, size/XS

#84 bump version to 3.6.1
  .osdk-scorecard.yaml
  Makefile
  README.md
  common/scripts/create-bundle.sh
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.1/ibm-auditlogging-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.1/operator.ibm.com_auditloggings_crd.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
  version/version.go
Labels: approved, lgtm, size/XL

#85 fix in place upgrade with hostaliases
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller_test.go
Labels: approved, lgtm, size/S

#81 readme updates
  README.md
Labels: approved, lgtm, size/M

#82 readme updates for case
  README.md
Labels: approved, lgtm, size/M

#86 Remove scaffold text
  pkg/controller/auditlogging/auditlogging_controller.go
Labels: approved, lgtm, size/XS

#88 move 3.6.1 into beta channel
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.1/ibm-auditlogging-operator.v3.6.1.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
Labels: approved, lgtm, size/XS
