Repository IBM/ibm-auditlogging-operator, pull requests merged in 2020-04, with the labels that each got.

#40 Made edits to README.md
  README.md
Labels: approved, lgtm, ok-to-test, size/M

#42 updated KC link
  README.md
Labels: approved, lgtm, ok-to-test, size/XS

#39 find and delete auditpolicy cr in make uninstall
  Makefile
Labels: approved, lgtm, size/XS

#44 bump fluentd image version
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  pkg/resources/containers.go
Labels: approved, lgtm, size/XS

#45 Create ibm-auditlogging-operand service account
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/containers.go
  pkg/resources/rbac.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#46 replaces field for olm
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#47 run policy controller and operator as restricted
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
  pkg/resources/containers.go
  pkg/resources/rbac.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XS

#48 allow operator to grant restricted scc
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XS

#49 steps to run operator locally
  README.md
Labels: approved, lgtm, size/XS

#50 uplift policy controller version to 3.5.0
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  pkg/resources/containers.go
Labels: approved, lgtm, size/XS

#51 fix matches bug
  pkg/resources/containers.go
Labels: approved, lgtm, size/XS

#52 manage operator dependency
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#53 Cv lint 35747
  README.md
  deploy/crds/operator.ibm.com_auditloggings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#54 create message key in http log records for qradar
  pkg/resources/containers.go
Labels: approved, lgtm, size/XS

#55 update missing csv changes
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#56 fix policy controller upgrade
  pkg/controller/auditlogging/auditlogging.go
  pkg/resources/rbac.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#57 more cv lint
  README.md
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/operator.ibm.com_auditloggings_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
Labels: approved, lgtm, size/M

#59 more cv updates
  README.md
  deploy/operator.yaml
  deploy/service_account.yaml
Labels: approved, lgtm, size/XS

#58 fix reconcile equals cases and remove port customization
  deploy/crds/operator.ibm.com_auditloggings_crd.yaml
  pkg/apis/operator/v1alpha1/auditlogging_types.go
  pkg/controller/auditlogging/auditlogging.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#60 fix index out of bounds for empty match
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#61 operands require affinity for case certification
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#62 fix upgrade to 3.6.0
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#63 up resources and update csv
  deploy/olm-catalog/ibm-auditlogging-operator/3.6.0/ibm-auditlogging-operator.v3.6.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/M

#64 fix naming conventions/logs
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#65 add tests
  Makefile
  README.md
  go.mod
  go.sum
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller_test.go
  pkg/resources/utils.go
  test/config/constants.go
  test/e2e/auditlogging_test.go
  test/e2e/main_test.go
  test/helpers/helpers.go
  test/testgroups/auditlogging_group.go
Labels: approved, lgtm, size/XL

#67 update ubi images
  build/Dockerfile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#66 codecov only unit tests
  Makefile
Labels: approved, lgtm, size/XS
