Repository IBM/ibm-auditlogging-operator, pull requests merged in 2020-02, with the labels that each got.

#1 updating Dockerfile UBI version and labels
  build/Dockerfile
  go.mod
Labels: approved, lgtm, size/XS

#2 make sdk install script executable
  common/scripts/install-operator-sdk.sh
Labels: approved, lgtm, size/XS

#3 updating Makefile to latest version
  Makefile
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/L

#4 updating image name to fix build failure
  Makefile
Labels: approved, lgtm, size/XS

#5 olm catalog and minor fixes
  Makefile
  common/Makefile.common.mk
  common/scripts/push-csv.sh
  deploy/crds/audit.policies.ibm.com_auditpolicies_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/csv-config.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/audit.policies.ibm.com_auditpolicies_crd.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/operator.ibm.com_auditloggings_crd.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certmanager/v1alpha1/zz_generated.openapi.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#6 use jetstack certmgr
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/apis/addtoscheme_certmanager_v1alpha1.go
  pkg/apis/certmanager/group.go
  pkg/apis/certmanager/v1alpha1/certificate_common.go
  pkg/apis/certmanager/v1alpha1/certificate_types.go
  pkg/apis/certmanager/v1alpha1/doc.go
  pkg/apis/certmanager/v1alpha1/register.go
  pkg/apis/certmanager/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/certmanager/v1alpha1/zz_generated.openapi.go
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/XL

#10 fixes for running in ibm-common-services namespace
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#9 Update operator package name to match ODLM
  deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
Labels: approved, lgtm, size/XS

#11 csv changes for operator hub and meta
  common/scripts/delete-csv.sh
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/M

#12 fix operator role
  common/scripts/push-csv.sh
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/S
