Repository IBM/ibm-auditlogging-operator, pull requests merged in 2020-11, with the labels that each got.

#133 feat(core): watch multinamespace
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/constant/constants.go
  controllers/k8sutil/cache.go
  controllers/resources/certificates.go
  controllers/util/utils.go
  controllers/util/utils_test.go
  go.mod
  go.sum
  main.go
Labels: approved, lgtm, size/XL

#134 fix(test): add eventually to fluentd deploy check
  controllers/commonaudit_controller_test.go
Labels: approved, lgtm, size/S

#135 fix(misc): remove leftover hardcoded ns and update readme
  README.md
  controllers/auditlogging_controller.go
  controllers/reconcile_auditlogging.go
Labels: approved, lgtm, size/S

#136 fix(upgrade): labelselector is immutable after creation
  controllers/util/utils.go
  controllers/util/utils_test.go
Labels: approved, lgtm, size/XS

#137 feat(core): deploy audit policy ctrl by default
  api/v1alpha1/auditlogging_types.go
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_auditloggings.yaml
  config/crd/bases/operator.ibm.com_auditloggings.yaml
  controllers/auditlogging_controller.go
  controllers/auditlogging_controller_test.go
  controllers/constant/constants.go
  controllers/reconcile_auditlogging.go
Labels: approved, lgtm, size/L

#138 fix(csv): add operandbindinfo
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S

#139 fix: update policy ctrl sha
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/constant/constants.go
Labels: approved, lgtm, size/XS

#140 fix: remove indent in env vars
  config/manager/manager.yaml
Labels: approved, lgtm, size/XS

#141 fix(config): fix manager yaml
  config/manager/manager.yaml
Labels: approved, lgtm, size/M

#142 fix: update shas and ubi8 image
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  controllers/constant/constants.go
Labels: approved, lgtm, size/S

#143 fix(cicd): add GOARCH to build targets
  Makefile
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, do-not-merge, size/S

#144 removing extra slash from power build
  Makefile
Labels: approved, size/XS

#145 chore(cicd): bump version to 3.8.2 for stable release
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, lgtm, size/S
