Repository IBM/ibm-auditlogging-operator, pull requests merged in 2020-03, with the labels that each got.

#13 fix rbac issues with policy controller validation
  deploy/role.yaml
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#14 cs-ca-clusterissuer
  deploy/crds/operator.ibm.com_auditloggings_crd.yaml
  deploy/operator.yaml
  pkg/apis/operator/v1alpha1/auditlogging_types.go
  pkg/controller/auditlogging/auditlogging.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#16 add verbose labels
  pkg/controller/auditlogging/auditlogging.go
  pkg/resources/containers.go
  pkg/resources/utils.go
  version/version.go
Labels: approved, lgtm, size/M

#17 instanceNamespace cannot be empty, but enabled can be empty
  deploy/crds/operator.ibm.com_auditloggings_crd.yaml
  pkg/apis/operator/v1alpha1/auditlogging_types.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#18 remove long comments in cm
  Makefile
  common/Makefile.common.mk
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/containers.go
Labels: approved, lgtm, size/M

#19 Newest csv
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/operator.ibm.com_auditloggings_crd.yaml
Labels: approved, lgtm, size/M

#20 moving to stable build of ubi 8 min
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#22 using correct ubi arch image for z and power
  build/Dockerfile.ppc64le
  build/Dockerfile.s390x
Labels: approved, lgtm, size/XS

#23 remove required in csv
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#24 hard code ibm-common-services namespace
  deploy/crds/operator.ibm.com_auditloggings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/operator.ibm.com_auditloggings_crd.yaml
  pkg/apis/operator/v1alpha1/auditlogging_types.go
  pkg/controller/auditlogging/auditlogging.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#25 updating fluentd image in csv
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#26 labels/annotations for metering/healthcheck
  pkg/resources/utils.go
Labels: approved, lgtm, size/S

#28 missing policy controller resources
  pkg/resources/containers.go
Labels: approved, lgtm, size/S

#27 remove unused args
  deploy/crds/operator.ibm.com_auditloggings_crd.yaml
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/operator.ibm.com_auditloggings_crd.yaml
  pkg/apis/operator/v1alpha1/auditlogging_types.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/M

#29 prep for red hat cert
  common/scripts/create-bundle.sh
  deploy/crds/operator.ibm.com_v1alpha1_auditlogging_cr.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#30 remove kube-audit match
  pkg/resources/containers.go
Labels: approved, lgtm, size/XS

#31 update owners
  OWNERS
Labels: approved, lgtm, size/XS

#35 branching off original branch to fix lint
  README.md
Labels: approved, lgtm, size/M

#32 Docs
  README.md
Labels: approved, lgtm, size/L

#33 metering annotations
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/S

#36 RH certification reqs
  .osdk-scorecard.yaml
  Makefile
  README.md
  cmd/manager/main.go
  deploy/crds/audit.policies.ibm.com_auditpolicies_crd.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/audit.policies.ibm.com_auditpolicies_crd.yaml
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/role.yaml
  pkg/controller/auditlogging/auditlogging.go
  pkg/controller/auditlogging/auditlogging_controller.go
  pkg/resources/containers.go
  pkg/resources/utils.go
Labels: approved, lgtm, size/L

#37 update csv channel
  deploy/olm-catalog/ibm-auditlogging-operator/ibm-auditlogging-operator.package.yaml
Labels: approved, lgtm, size/XS

#38 operator image tag set to 3.5.0
  deploy/olm-catalog/ibm-auditlogging-operator/3.5.0/ibm-auditlogging-operator.v3.5.0.clusterserviceversion.yaml
  deploy/operator.yaml
Labels: approved, lgtm, size/XS
