Repository IBM/ibm-auditlogging-operator, pull requests merged in 2021-08, with the labels that each got.

#186 add type
  bundle/manifests/audit.policies.ibm.com_auditpolicies.yaml
Labels: size/XS

#187 min Kube Version
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
Labels: size/XS

#188 update golang
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS

#189 rh mirroring
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
Labels: size/XS

#190 remove subresource
  bundle/manifests/operator.ibm.com_auditloggings.yaml
  bundle/manifests/operator.ibm.com_commonaudits.yaml
Labels: size/XS

#191 fluentd enabled true
  config/samples/operator_v1alpha1_auditlogging.yaml
Labels: needs-ok-to-test, size/XS

#192 Fix crd
  bundle/manifests/operator.ibm.com_auditloggings.yaml
  bundle/manifests/operator.ibm.com_commonaudits.yaml
  config/crd/bases/operator.ibm.com_auditloggings.yaml
  config/crd/bases/operator.ibm.com_commonaudits.yaml
  go.mod
  go.sum
Labels: size/XL

#193 add labels back
  bundle/manifests/operator.ibm.com_auditloggings.yaml
  bundle/manifests/operator.ibm.com_commonaudits.yaml
  config/crd/bases/operator.ibm.com_auditloggings.yaml
  config/crd/bases/operator.ibm.com_commonaudits.yaml
Labels: size/S

#194 fix dep api
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: size/XS

#196 version bump
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#197 opt-in CICD automation
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  base_images.json
  common/scripts/config_docker.sh
Labels: size/S, needs-ok-to-test
