Repository IBM/ibm-auditlogging-operator, pull requests merged in 2021-12, with the labels that each got.

#215 bump version for CS 3.15.0
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#216 remove codecov
  Makefile
  common/scripts/codecov.sh
Labels: size/L

#217 remove systemd source to remove privileged access #51298
  api/v1alpha1/auditlogging_types.go
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  bundle/manifests/operator.ibm.com_auditloggings.yaml
  config/crd/bases/operator.ibm.com_auditloggings.yaml
  config/rbac/role.yaml
  config/samples/operator_v1alpha1_auditlogging.yaml
  controllers/auditlogging_controller.go
  controllers/commonaudit_controller.go
  controllers/reconcile_auditlogging.go
  controllers/reconcile_commonaudit.go
  controllers/resources/configmaps_v1alpha1.go
  controllers/resources/containers.go
  controllers/resources/deployments.go
  controllers/resources/job.go
  controllers/resources/rbac.go
  controllers/util/utils.go
  controllers/util/utils_test.go
Labels: approved, lgtm, size/L
