Repository IBM/ibm-auditlogging-operator, pull requests merged in 2021-06, with the labels that each got.

#173 update ubi and bump version for 3.8
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  version/version.go
Labels: size/XS

#174 Fix prow build break and version number
  Dockerfile.ppc64le
  Dockerfile.s390x
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: lgtm, size/S

#175 bump version
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#176 fix versioning
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#177 use latest ubi
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  common/Makefile.common.mk
Labels: size/XS
