Repository IBM/ibm-auditlogging-operator, pull requests merged in 2021-07, with the labels that each got.

#178 make hidden
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
Labels: size/XS

#179 update license
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
Labels: size/S

#180 bump version
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#183 Deprecated resources
  bundle/manifests/audit.policies.ibm.com_auditpolicies.yaml
  config/samples/audit.policies_v1alpha1_auditpolicy.yaml
Labels: needs-ok-to-test, size/M

#181 fixed the first override
  bundle/manifests/audit.policies.ibm.com_auditpolicies.yaml
Labels: needs-ok-to-test, size/XS

#184 fixed the other two yaml files
  bundle/manifests/operator.ibm.com_auditloggings.yaml
  bundle/manifests/operator.ibm.com_commonaudits.yaml
Labels: needs-ok-to-test, size/L

#185 update qemu
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: size/XS
