Repository IBM/ibm-auditlogging-operator, pull requests merged in 2021-03, with the labels that each got.

#158 fix(cert-manager): Allow label updates 3.8
  controllers/reconcile_auditlogging.go
  controllers/reconcile_commonaudit.go
  go.mod
Labels: lgtm, size/S

#159 q1 case changes
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S

#157 fix(cert-manager): allow label updates
  controllers/reconcile_auditlogging.go
  controllers/reconcile_commonaudit.go
  go.mod
Labels: lgtm, size/S

#161 Update ibm-auditlogging-operator.clusterserviceversion.yaml
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
Labels: size/XS
