Repository IBM/ibm-auditlogging-operator, pull requests merged in 2022-11, with the labels that each got.

#255 Update operand version for 3.22.0 and updated go version to 1.18.8
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: size/S

#256 Update operand version for 3.19.7 and updated go version to 1.18.8
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, size/M

#259 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS

#260 New prow cluster name
  common/Makefile.common.mk
Labels: size/XS
