Repository IBM/ibm-auditlogging-operator, pull requests merged in 2022-05, with the labels that each got.

#232 fix aqua issues
  go.mod
  go.sum
Labels: lgtm, size/M

#233 Included replaces image in audit logging csv yaml file
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#235 version bumpup for CS 3.19.0 #53499
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, lgtm, size/M

#236 go version updated to resolve twistlock issue #53484
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, size/XS, lgtm
