Repository IBM/ibm-auditlogging-operator, pull requests merged in 2022-04, with the labels that each got.

#229 version bumpup for CS 3.18.0 #53055
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, lgtm, size/M

#230 Recertification comment addressed for Operator name defined in spec 1.16.13
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manifests/bases/ibm-auditlogging-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#231 movement to icr.io
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  common/config/.hadolint.yml
  config/manager/manager.yaml
Labels: size/S
