Repository IBM/ibm-auditlogging-operator, pull requests merged in 2022-02, with the labels that each got.

#220 version bump for CS 3.16.0 #51968
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: lgtm, size/M

#221 version bump for EUS 3.8.5
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: approved, size/S, lgtm

#223 Fix for fluentd pod restart #52190
  controllers/resources/deployments.go
  controllers/util/utils.go
Labels: approved, size/S, lgtm

#224 fix for fluentd restarts
  controllers/reconcile_auditlogging.go
  controllers/reconcile_commonaudit.go
  controllers/resources/deployments.go
  controllers/util/utils.go
  controllers/util/utils_test.go
Labels: lgtm, size/M

#225 Fluent version update
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, size/XS, lgtm

#226 Go version updated to 1.17.7 #52301
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, size/XS, lgtm
