Repository IBM/ibm-auditlogging-operator, pull requests merged in 2023-01, with the labels that each got.

#265 operand and operator version bumup for 3.24.0 #56851
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/M

#264 operand version bumup in operator for 3.19.8 #56330
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: approved, size/S

#266 Artifactory image location updated for audit logging #56863
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/scripts/config_docker.sh
Labels: size/S

#267 Artifactory image location updated for audit logging #56863
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
  Makefile
  common/scripts/config_docker.sh
Labels: approved, size/S

#268 go version updated to 1.18.10
  Dockerfile
  Dockerfile.ppc64le
  Dockerfile.s390x
Labels: approved, size/XS

#269 move version from 3.26.0 to 3.25.1
  bundle/manifests/ibm-auditlogging-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
  version/version.go
Labels: size/S
